root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - google
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:jsdoc/recommended
  - plugin:yaml/recommended
  - plugin:vue/vue3-recommended
  - '@vue/eslint-config-prettier'
plugins:
  - vue
  - html
  - eslint-plugin-tsdoc
  - '@typescript-eslint'
  - vuejs-accessibility
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
  createDefaultProgram: true
  project: ./tsconfig.json
rules:
  new-cap: off
  no-invalid-this: off
  no-unused-vars: warn
  require-jsdoc: warn
  tsdoc/syntax: warn
  jsdoc/require-param: ['off', { enableRootFixer: false }]
  jsdoc/require-param-type: off
  jsdoc/require-returns: off
  jsdoc/require-returns-type: off
  jsdoc/require-returns-description: off
  valid-jsdoc: off
  import/no-named-as-default: off
  vue/html-self-closing: [error, html: { void: always }]
  vue/multi-word-component-names: warn
settings:
  import/resolver:
    typescript: {}
    alias:
      map:
        - ['@', './src']
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
        - .vue
