extends:
  - stylelint-config-html/vue
  - stylelint-config-standard-scss
  - stylelint-config-recommended-vue
  - stylelint-config-prettier
plugins:
  - stylelint-order
  - stylelint-prettier
ignoreFiles:
  - 'dist/**/*'
rules:
  prettier/prettier: true
  at-rule-no-unknown: null
  color-function-notation: legacy
  no-descending-specificity: null
  selector-class-pattern: null
